<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report.proto

namespace Report;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>report.Report</code>
 */
class Report extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.report.User user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>.report.Service service = 3;</code>
     */
    protected $service = null;
    /**
     * Generated from protobuf field <code>.report.ServiceType service_type = 4;</code>
     */
    protected $service_type = null;
    /**
     * Generated from protobuf field <code>string name = 5;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string email = 6;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string no_handphone = 7;</code>
     */
    protected $no_handphone = '';
    /**
     * Generated from protobuf field <code>string status = 8;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string description = 9;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string created_at = 10;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 11;</code>
     */
    protected $updated_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type \Report\User $user
     *     @type \Report\Service $service
     *     @type \Report\ServiceType $service_type
     *     @type string $name
     *     @type string $email
     *     @type string $no_handphone
     *     @type string $status
     *     @type string $description
     *     @type string $created_at
     *     @type string $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Report::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.report.User user = 2;</code>
     * @return \Report\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.report.User user = 2;</code>
     * @param \Report\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Report\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.report.Service service = 3;</code>
     * @return \Report\Service
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>.report.Service service = 3;</code>
     * @param \Report\Service $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkMessage($var, \Report\Service::class);
        $this->service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.report.ServiceType service_type = 4;</code>
     * @return \Report\ServiceType
     */
    public function getServiceType()
    {
        return $this->service_type;
    }

    /**
     * Generated from protobuf field <code>.report.ServiceType service_type = 4;</code>
     * @param \Report\ServiceType $var
     * @return $this
     */
    public function setServiceType($var)
    {
        GPBUtil::checkMessage($var, \Report\ServiceType::class);
        $this->service_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 6;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string no_handphone = 7;</code>
     * @return string
     */
    public function getNoHandphone()
    {
        return $this->no_handphone;
    }

    /**
     * Generated from protobuf field <code>string no_handphone = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNoHandphone($var)
    {
        GPBUtil::checkString($var, True);
        $this->no_handphone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 8;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 9;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 10;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 11;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

}

