<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report.proto

namespace Report;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>report.ReportsResponse</code>
 */
class ReportsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .report.Report reports = 1;</code>
     */
    private $reports;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Report\Report[]|\Google\Protobuf\Internal\RepeatedField $reports
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Report::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .report.Report reports = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReports()
    {
        return $this->reports;
    }

    /**
     * Generated from protobuf field <code>repeated .report.Report reports = 1;</code>
     * @param \Report\Report[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReports($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Report\Report::class);
        $this->reports = $arr;

        return $this;
    }

}

