<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report.proto

namespace Report;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>report.UpdateReportRequest</code>
 */
class UpdateReportRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>uint64 service_id = 3;</code>
     */
    protected $service_id = 0;
    /**
     * Generated from protobuf field <code>uint64 service_type_id = 4;</code>
     */
    protected $service_type_id = 0;
    /**
     * Generated from protobuf field <code>string name = 5;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string email = 6;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string no_handphone = 7;</code>
     */
    protected $no_handphone = '';
    /**
     * Generated from protobuf field <code>string status = 8;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string description = 9;</code>
     */
    protected $description = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $service_id
     *     @type int|string $service_type_id
     *     @type string $name
     *     @type string $email
     *     @type string $no_handphone
     *     @type string $status
     *     @type string $description
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Report::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 service_id = 3;</code>
     * @return int|string
     */
    public function getServiceId()
    {
        return $this->service_id;
    }

    /**
     * Generated from protobuf field <code>uint64 service_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServiceId($var)
    {
        GPBUtil::checkUint64($var);
        $this->service_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 service_type_id = 4;</code>
     * @return int|string
     */
    public function getServiceTypeId()
    {
        return $this->service_type_id;
    }

    /**
     * Generated from protobuf field <code>uint64 service_type_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServiceTypeId($var)
    {
        GPBUtil::checkUint64($var);
        $this->service_type_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 6;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string no_handphone = 7;</code>
     * @return string
     */
    public function getNoHandphone()
    {
        return $this->no_handphone;
    }

    /**
     * Generated from protobuf field <code>string no_handphone = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNoHandphone($var)
    {
        GPBUtil::checkString($var, True);
        $this->no_handphone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 8;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 9;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

}

